### ISSUE TITLE
add to MELPA

### ISSUE THREAD

**Issue by stardiviner** [ptrv/company-lua#1]
hope can be installed from MELPA.

**Comment by stardiviner** [comment]
I added a recipe on MELPA.
https://github.com/melpa/melpa/pull/3718

**Comment by ptrv** [comment]
Sorry for my late response. Thank you for doing this!

**Comment by stardiviner** [comment]
It's fine. I don't know whether MELPA will accept my recipe, maybe need add some comments in file.
I will update it here.

**Comment by ptrv** [comment]
I merged already pull request #2 to make the package work with melpa.

**Comment by stardiviner** [comment]
@ptrv  https://github.com/melpa/melpa/pull/3718#issuecomment-203744496 there is update.
