### ISSUE TITLE
Active lua process when there is no lua interpreter

### ISSUE THREAD

**Issue by rexim** [ptrv/company-lua#4]
### System Information
- OS: NixOS 16.03
- Emacs 24.5.2 from the official stable nixpkgs channel
- company 20160429.1339 from MELPA
- company-lua 20160330.313 from MELPA
### Steps to reproduce
- Don't have lua interpreter installed on your system :) (well, at least `(executable-find "lua")` should return `nil` for your currently running instance of Emacs)
- Have `company` and `company-lua` configured like that: [company-rc.el](https://github.com/rexim/dotfiles/blob/5713e10e86a50e53a4e67e7caff0113c52b4ae25/.emacs.rc/company-rc.el#L4)
- Start Emacs
- `M-x find-file RET ~/khooy.lua RET`
- `M-x company-complete RET`
- `C-x C-c`
### Observed

Emacs says that there are active processes. And one of them is the lua process.
### Expected

IMO Emacs should quit clearly.
### Commentary

Well, I think I actually know why this happens. This is because when the user doesn't have the lua interpreter we put `nil` as the `PROGRAM` argument of the `start-process` function at [company-lua.el#L83](https://github.com/ptrv/company-lua/blob/d1384d7c709ed157bc7dcd8f2cfdf6212299b2bf/company-lua.el#L83). And the docs say:

> `PROGRAM` is the program file name.  It is searched for in `exec-path` (which see).  **If `nil`, just associate a pty with the buffer**.  Remaining arguments are strings to give program as arguments.

This is probably what happens in our case. The question is what do we have to do when the lua interpreter is missing? Just silently do nothing or say "Hey! You don't have lua. Please install it to autocomplete things" somewhere in the `*Messages*`? I'd like to go with the second option. :)

**Comment by ptrv** [comment]
Thanks for pointing this out.

Fixed with https://github.com/ptrv/company-lua/commit/ba0a6bafdb479edb5c437b775c6f884472db5a94

**Comment by rexim** [comment]
Cool! Thank you very much!
